name: EntityCages
version: '${project.version}'
main: mbarrr.github.entitycages.EntityCages
api-version: 1.16
authors: [ MBarrr ]
website: https://github.com/MBarrr
commands:
  getCage:
    usage: /getcage
    description: §eUsed to get a cage item.
  excludeEntity:
    usage: /excludeEntity <EntityType> <true/false>
    description: Leave arguments empty to view excluded entities
  excludeName:
    usage: /excludeName <Name> <true/false>
    description: Leave arguments empty to view excluded names